version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-sol-index
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_network

volumes:
  mongodb_data:

networks:
  mongo_network:
