name: Build and Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Backend
        run: |
          echo "${{ secrets.ENV }}" > .env
          pnpm install
          pnpm build
          rm -rf node_modules
          tar -czf backend.tar.gz dist pnpm-lock.yaml package.json .env

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "backend.tar.gz"
          target: "/home/ubuntu/deploy"

      - name: Run remote deploy script on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            set -e  # ← This makes the script stop immediately on error

            sudo mkdir -p /home/ubuntu/apps/backend
            sudo chown -R ubuntu:ubuntu /home/ubuntu/apps/backend

            sudo tar -xzf /home/ubuntu/deploy/backend.tar.gz -C /home/ubuntu/apps/backend
            sudo rm -rf /home/ubuntu/deploy/backend.tar.gz

            source ~/.nvm/nvm.sh
            nvm use node

            cd /home/ubuntu/apps/backend

            pnpm install

            echo "Run migrations 🚀"
            pnpm migration:run-build
            echo "Finish run migrations ✅"

            pm2 flush backend || true
            pm2 delete backend || true
            pm2 start dist/main.js --name="backend"
